version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - infra-network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - infra-network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: mydb
      DB_POSTGRESDB_USER: admin
      DB_POSTGRESDB_PASSWORD: admin123
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: samuelabrao2006@gmail.com
      N8N_BASIC_AUTH_PASSWORD: 1@Samuel1501
      N8N_HOST: n8n.local
      N8N_PORT: 5678
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - infra-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - infra-network

volumes:
  postgres_data:
  minio_data:
  n8n_data:

networks:
  infra-network:
    driver: bridge